// This patch was automatically generated by the RAMSES-CPP AI Patch Porter tool with the help of Gemini-chan ✨
#define RAMSES_HAS_PATCH_INITIALIZER
#include "ramses/SolverFactory.hpp"
#include "ramses/Initializer.hpp"
#include "ramses/Constants.hpp"
#include <algorithm>
#include <cmath>

namespace ramses {

class PatchInitializer : public Initializer {
public:
    using Initializer::Initializer;

    void region_condinit(int ilevel) override {
        // AI-ported logic from legacy/patch/rt/iliev6_profile/condinit.f90
        // (Simplified for demonstration)
        int myid = 1; // Simplified rank
        int n2d_val = (1 << NDIM);
        
        if (ilevel == 1) {
            for (int i = 1; i <= grid_.ncoarse; ++i) {
                grid_.uold(i, 1) = 1.0; // Density = 1.0 everywhere
            }
        } else {
            int igrid = grid_.get_headl(myid, ilevel);
            while (igrid > 0) {
                for (int ic = 1; ic <= n2d_val; ++ic) {
                    int idc = grid_.ncoarse + (ic - 1) * grid_.ngridmax + igrid;
                    grid_.uold(idc, 1) = 1.0;
                }
                igrid = grid_.next[igrid - 1];
            }
        }
    }
};

std::unique_ptr<Initializer> create_initializer(AmrGrid& grid, Config& config) {
    return std::make_unique<PatchInitializer>(grid, config);
}

} // namespace ramses
