// This patch was automatically generated by the RAMSES-CPP AI Patch Porter tool with the help of Gemini-chan ✨
#define RAMSES_HAS_PATCH_HYDRO
#include "ramses/SolverFactory.hpp"
#include "ramses/HydroSolver.hpp"
#include "ramses/Constants.hpp"
#include "ramses/MpiManager.hpp"
#include <cmath>
#include <algorithm>

namespace ramses {

class PatchHydroSolver : public HydroSolver {
public:
    using HydroSolver::HydroSolver;

    real_t compute_courant_step(int ilevel, real_t dx, real_t gamma, real_t courant_factor) override {
        real_t dt_max = 1e30;
        int myid = MpiManager::instance().rank() + 1;
        int n2d_val = (1 << NDIM);

        int igrid = grid_.get_headl(myid, ilevel);
        while (igrid > 0) {
            for (int ic = 1; ic <= n2d_val; ++ic) {
                int id = grid_.ncoarse + (ic - 1) * grid_.ngridmax + igrid;
                if (grid_.son[id - 1] > 0) continue; // Only leaf cells

                real_t d = std::max(grid_.uold(id, 1), 1e-10);
                real_t v2 = 0.0;
                for (int i = 1; i <= 3; ++i) {
                    real_t v = grid_.uold(id, 1 + i) / d;
                    v2 += v * v;
                }
                real_t p = std::max((grid_.uold(id, 5) - 0.5 * d * v2) * (gamma - 1.0), d * 1e-10);
                real_t cs = std::sqrt(gamma * p / d);
                real_t v_mag = std::sqrt(v2);

                // Bondi specific or standard Courant
                dt_max = std::min(dt_max, courant_factor * dx / (v_mag + cs));

                // Account for acceleration if poisson is active
                for (int idim = 1; idim <= NDIM; ++idim) {
                    real_t acc = std::abs(grid_.f(id, idim));
                    if (acc > 0) dt_max = std::min(dt_max, courant_factor * std::sqrt(dx / acc));
                }
            }
            igrid = grid_.next[igrid - 1];
        }
        return dt_max;
    }
};

std::unique_ptr<HydroSolver> create_hydro_solver(AmrGrid& grid, Config& config) {
    return std::make_unique<PatchHydroSolver>(grid, config);
}

} // namespace ramses
