// This patch was automatically generated by the RAMSES-CPP AI Patch Porter tool with the help of Gemini-chan ✨
#define RAMSES_HAS_PATCH_COOLING
#include "ramses/SolverFactory.hpp"
#include "ramses/CoolingSolver.hpp"
#include <algorithm>
#include <cmath>

namespace ramses {

class PatchCoolingSolver : public CoolingSolver {
public:
    using CoolingSolver::CoolingSolver;

    void apply_cooling(int ilevel, real_t dt) override {
        // AI-ported logic from legacy/patch/hydro/eos/cooling_fine.f90
        // (Simplified for demonstration)
        for (int i = 1; i <= grid_.ncell; ++i) {
            if (grid_.son[i - 1] > 0) continue; 
            
            real_t d = grid_.uold(i, 1);
            if (d < 1e-6) {
                grid_.uold(i, 1) = 1e-6; // Density floor patch
            }
        }
    }
};

std::unique_ptr<CoolingSolver> create_cooling_solver(AmrGrid& grid, Config& config) {
    return std::make_unique<PatchCoolingSolver>(grid, config);
}

} // namespace ramses
